baseURL = 'https://featherwallet.org/'
languageCode = 'en-us'
title = 'Feather Wallet'
theme = 'feather'
defaultContentLanguage = 'en'
rssLimit = 20

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Download"
    pre = "download"
    url = "/download/"
    weight = 2
  [[menu.main]]
    name = "Changelog"
    pre = "changelog"
    url = "/changelog/"
    weight = 3
  [[menu.main]]
    name = "Screenshots"
    pre = "screenshots"
    url = "/screenshots/"
    weight = 4
  [[menu.main]]
    name = "Docs"
    pre = "docs"
    url = "https://docs.featherwallet.org"
    weight = 5
  [[menu.main]]
    name = "Help"
    pre = "help"
    url = "https://docs.featherwallet.org/guides/report-an-issue"
    weight = 6
  [[menu.link]]
    name = "Clearnet"
    pre = "clearnet"
    url = "https://featherwallet.org"
    weight = 1
  [[menu.link]]
    name = "Onion"
    pre = "onion"
    params.icon = "<img src='/img/onion-tor.avif'>"
    url = "http://featherdvtpi7ckdbkb2yxjfwx3oyvr3xjz3oo4rszylfzjdg6pbm3id.onion"
    weight = 2
  [[menu.link]]
    name = "I2P"
    pre = "i2p"
    params.icon = "<img src='/img/itoopie.png'>"
    url = "http://featherwallet.i2p/?i2paddresshelper=6mERqxqRWl34VSb0s8pRH7oACl-CEJX7njZQpNT4v9DqYRGrGpFaXfhVJvSzylEfugAKX4IQlfueNlCk1Pi~0OphEasakVpd-FUm9LPKUR-6AApfghCV-542UKTU-L~Q6mERqxqRWl34VSb0s8pRH7oACl-CEJX7njZQpNT4v9DqYRGrGpFaXfhVJvSzylEfugAKX4IQlfueNlCk1Pi~0OphEasakVpd-FUm9LPKUR-6AApfghCV-542UKTU-L~Q6mERqxqRWl34VSb0s8pRH7oACl-CEJX7njZQpNT4v9DqYRGrGpFaXfhVJvSzylEfugAKX4IQlfueNlCk1Pi~0OphEasakVpd-FUm9LPKUR-6AApfghCV-542UKTU-L~Q6mERqxqRWl34VSb0s8pRH7oACl-CEJX7njZQpNT4v9DqYRGrGpFaXfhVJvSzylEfugAKX4IQlfueNlCk1Pi~0EjVQ95SQI~X-Dww2pdxgbSYWstFAdT0ReHljNSSBsY0BQAEAAcAAA=="
    weight = 3


[languages]
  [languages.en]
    title = 'Feather Wallet'
    weight = 1

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
